name: CMake Unit Tests

on:
  push:
    branches: [ working ]
  pull_request:
    branches: [ working ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean build folder (important!)
      - name: Clean build directory
        run: |
          rm -rf build

      - name: Configure project with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure
